name: AUDIO

#Seanet encoder config
encoder:
  in_channels: 1
  base_channels: 32
  dimension: 256
  n_residual_layers: 3
  ratios: [8, 5, 4, 2]         
  kernel_size: 7
  last_kernel_size: 7
  residual_kernel_size: 3
  dilation_base: 2

#Transformer config
transformer:
  d_model: 256
  n_heads: 2
  n_layers: 4
  d_ff: 1024
  max_seq_len: 256
  max_audio_len: 5000
  dropout: 0.0
  conditional: true
  use_flash: true
