name: discrete_encodec

freeze_encoder: true
use_processor: true
sample_rate: 24000

#Seanet encoder config
encoder:
  _target_: modules.models.Encodec

#Transformer Decocer config
transformer:
  _target_: modules.transformer2.TransformerDecoderAudioConditioned

  # --- Model dimensions ---
  d_model: 512                
  d_ff: 2048                  
  n_heads: 8                  
  num_kv_heads: 4
  n_layers: 8      
  dropout: 0.0
  audio_drop: 0.0    
  compression: null
  use_flash: true            
  conditional: false           # If true, expects class embeddings

  rope_base: 10000.0           # Base frequency (common: 10000)

