name: EXP_CONF

use_spectrogram: true

#Conformer encoder config
encoder:
  _target_: modules.conf.ConformerEncoder
  feat_in: 80
  n_layers: 12
  d_model: 256
  subsampling_factor: 8
  ff_expansion_factor: 4
  n_heads: 8
  num_kv_heads: 2
  conv_kernel_size: 9
  dropout: 0.0
  dropout_att: 0.0

#Transformer Decocer config
transformer:
  _target_: modules.models.TransformerDecoderAudioConditioned
  d_model: 512
  n_heads: 4
  n_layers: 8
  d_ff: 1024
  max_seq_len: 513
  max_audio_len: 5000
  dropout: 0.0
  conditional: false
  use_flash: true