name: CTC

freeze_encoder: true
use_processor: true
sample_rate: 24000

#Seanet encoder config
encoder:
  _target_: modules.models3.Encodec

#Transformer Decocer config
transformer:
  _target_: modules.trainer3.TransformerEncoderCTC

  # --- Model dimensions ---
  d_model: 512                
  n_heads: 8                  
  n_layers: 8      
  dropout: 0.0
  use_flash: true            

