defaults:
  - default.yaml
  - model: audio_codec
  - _self_


# Add audio encoder lr
optimizer:
  lr_audio: 1e-3

data_split_folder: null
window_seconds: 30

is_discrete: true
grid_ms: 20
augment: false

seed: 42

tags: [audio]
