#Data Config
root_folder: ../data
batch_size: 4
validation_split: 0.2
diff_list: 
  - Expert
  - Hard
  - Medium
  - Easy
inst_list: 
  - Single
max_length: 513


#Optimizer Config
optimizer:
  lr: 5e-5
  weight_decay: 0.01
  warmup_steps: 384
  max_steps: 68000


#Trainer
max_epochs: 200
gpus: 1
precision: 'bf16'


#Wandb
tags:  ???
