#Data Config
root_folder: extracted_songs/
batch_size: 128
validation_split: 0.8
diff_list: 
  - Expert
  - Hard
  - Medium
  - Easy
inst_list: 
  - Single
max_length: 256


#Optimizer Config
optimizer:
  lr: 5e-5
  weight_decay: 0.01
  warmup_steps: 384
  max_steps: 6800


#Trainer
max_epochs: 200
gpus: 1


#Wandb
tags:  ???